[framework]
name = "happyx"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
approach = "Realistic"
classification = "Fullstack"
database = "postgres"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "None"
webserver = "None"
versus = "httpbeast, jester, prologue, basolato"
